export const MAIN_PAGE_FILMS_DISPLAY_STEP = 8;
export const MOVIE_PAGE_FILMS_TO_DISPLAY = 4;

export const REVIEWS_PER_COLUMN = 3;

export const PREVIEW_PLAY_TIMEOUT = 1000;

export const MAX_GENRES_IN_GENRES_LIST = 10;
